"""
Integration Test for Trade Tracking with Real Order Flow

Tests the complete end-to-end flow:
- Order placement with trade_id generation
- Order filling with transaction creation
- Trade record auto-creation
- Performance analytics API endpoints
"""

import uuid
import pytest
from datetime import datetime
from sqlalchemy import select

from app.models.strategies import Fund, Order, Transaction, Trade
from app.services.analytics.trade_builder import TradeBuilder


@pytest.mark.asyncio
async def test_complete_trade_flow_with_trade_builder(async_session):
    """
    Test complete flow: place buy order -> fill -> place sell order -> fill -> trade closed.
    Simulates what the strategy engine does.
    """
    # Create test fund
    fund = Fund(
        id=str(uuid.uuid4()),
        name="Integration Test Fund",
        mode="sim",
        balance=100000.0,
        status="active",
        strategy_id="monkey_darts",
        size_per_trade=1000.0
    )
    async_session.add(fund)
    await async_session.commit()
    
    # Step 1: Strategy engine places BUY order (generates trade_id)
    trade_id = str(uuid.uuid4())
    buy_order_id = str(uuid.uuid4())
    
    buy_order = Order(
        id=buy_order_id,
        fund_id=fund.id,
        trade_id=trade_id,  # Generated by strategy engine
        symbol="AAPL",
        side="buy",
        quantity=10.0,
        order_type="market",
        status="pending",
        submitted_at=datetime.utcnow(),
        estimated_price=150.0
    )
    async_session.add(buy_order)
    await async_session.commit()
    
    print(f"✓ Buy order created with trade_id: {trade_id}")
    
    # Step 2: Order fills (order polling detects fill)
    buy_order.status = "filled"
    buy_order.filled_at = datetime.utcnow()
    buy_order.filled_qty = 10.0
    buy_order.filled_avg_price = 150.50
    
    # Transaction created with trade_id inherited from order
    buy_txn = Transaction(
        id=str(uuid.uuid4()),
        order_id=buy_order.id,
        fund_id=fund.id,
        trade_id=trade_id,  # Inherited from order
        symbol="AAPL",
        side="buy",
        quantity=10.0,
        price=150.50,
        total_value=1505.0,
        timestamp=datetime.utcnow()
    )
    async_session.add(buy_txn)
    await async_session.commit()
    
    print(f"✓ Buy transaction created with trade_id: {trade_id}")
    
    # Step 3: Trade Builder creates Trade record
    trade_builder = TradeBuilder(async_session)
    trade = await trade_builder.create_trade_from_entry(
        trade_id=trade_id,
        fund_id=fund.id,
        symbol="AAPL",
        entry_order_id=buy_order.id,
        entry_transactions=[buy_txn],
        strategy_id="monkey_darts",
        ai_confidence=0.85
    )
    await async_session.commit()
    
    print(f"✓ Trade record created: {trade.id}, status={trade.status}")
    
    # Verify trade is open
    assert trade.status == "open"
    assert trade.realized_pnl is None
    
    # Step 4: Later, strategy decides to exit position
    # Find the open trade
    open_trade = await trade_builder.get_open_trade_for_symbol(
        fund_id=fund.id,
        symbol="AAPL"
    )
    assert open_trade is not None
    assert open_trade.id == trade_id
    
    print(f"✓ Found open trade for AAPL: {open_trade.id}")
    
    # Step 5: Place SELL order (links to existing trade_id)
    sell_order_id = str(uuid.uuid4())
    
    sell_order = Order(
        id=sell_order_id,
        fund_id=fund.id,
        trade_id=trade_id,  # Same trade_id as entry
        symbol="AAPL",
        side="sell",
        quantity=10.0,
        order_type="market",
        status="pending",
        submitted_at=datetime.utcnow(),
        estimated_price=160.0
    )
    async_session.add(sell_order)
    await async_session.commit()
    
    print(f"✓ Sell order created with trade_id: {trade_id}")
    
    # Step 6: Sell order fills
    sell_order.status = "filled"
    sell_order.filled_at = datetime.utcnow()
    sell_order.filled_qty = 10.0
    sell_order.filled_avg_price = 160.25
    
    sell_txn = Transaction(
        id=str(uuid.uuid4()),
        order_id=sell_order.id,
        fund_id=fund.id,
        trade_id=trade_id,  # Same trade_id
        symbol="AAPL",
        side="sell",
        quantity=10.0,
        price=160.25,
        total_value=1602.50,
        timestamp=datetime.utcnow()
    )
    async_session.add(sell_txn)
    await async_session.commit()
    
    print(f"✓ Sell transaction created with trade_id: {trade_id}")
    
    # Step 7: Trade Builder closes the trade
    closed_trade = await trade_builder.close_trade(
        trade_id=trade_id,
        exit_order_id=sell_order.id,
        exit_transactions=[sell_txn]
    )
    await async_session.commit()
    
    print(f"✓ Trade closed: P&L=${closed_trade.realized_pnl:.2f} ({closed_trade.realized_pnl_percent:.2f}%)")
    
    # Verify complete trade record
    assert closed_trade.status == "closed"
    assert closed_trade.entry_price == 150.50
    assert closed_trade.exit_price == 160.25
    assert closed_trade.realized_pnl == pytest.approx(97.50, abs=0.1)  # (160.25 - 150.50) * 10
    assert closed_trade.hold_duration_seconds is not None
    
    # Verify we can query it
    result = await async_session.execute(
        select(Trade).where(Trade.id == trade_id)
    )
    queried_trade = result.scalar_one()
    
    assert queried_trade.id == trade_id
    assert queried_trade.symbol == "AAPL"
    assert queried_trade.realized_pnl == pytest.approx(97.50, abs=0.1)
    
    # Verify all transactions have the same trade_id
    result = await async_session.execute(
        select(Transaction).where(Transaction.trade_id == trade_id)
    )
    transactions = result.scalars().all()
    
    assert len(transactions) == 2
    assert all(t.trade_id == trade_id for t in transactions)
    
    # Verify all orders have the same trade_id
    result = await async_session.execute(
        select(Order).where(Order.trade_id == trade_id)
    )
    orders = result.scalars().all()
    
    assert len(orders) == 2
    assert all(o.trade_id == trade_id for o in orders)
    
    print("\n✅ Complete trade flow validated!")
    print(f"   Trade ID: {trade_id}")
    print(f"   Symbol: AAPL")
    print(f"   Entry: ${closed_trade.entry_price:.2f} @ {closed_trade.entry_time}")
    print(f"   Exit: ${closed_trade.exit_price:.2f} @ {closed_trade.exit_time}")
    print(f"   P&L: ${closed_trade.realized_pnl:.2f} ({closed_trade.realized_pnl_percent:.2f}%)")
    print(f"   Duration: {closed_trade.hold_duration_seconds}s")
    print(f"   Orders: {len(orders)} (buy + sell)")
    print(f"   Transactions: {len(transactions)} (buy + sell)")

