export type StockData = {
  ticker: string;
  price: number;
  last_trade_price?: number | null;
  prev_open: number;
  prev_high: number;
  prev_low: number;
  prev_close: number;
  prev_volume: number;
  today_vol?: number | null;
  rv14?: number | null;
  rv_lw?: number | null;
  change_close?: number | null;
  change_close_pct?: number | null;
  type?: string | null;
  primary_exchange?: string | null;
  sic_description?: string | null;
  market_cap?: number | null;
  public_float?: number | null;
};
