"""Core computation logic for screener filtering and sorting."""
from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional

from app.services.screener.screener_data import ScreenerDataLoader
from app.services.screener.screener_filters import (
    is_allowed_exchange,
    is_likely_etf,
    passes_price_filter,
    passes_volume_filter,
)
from app.services.screener.screener_snapshot import extract_snapshot_data


class ScreenerCompute:
    """Handles screener computation: filtering, sorting, and result generation."""
    
    def __init__(self, data_loader: ScreenerDataLoader):
        self.logger = logging.getLogger("app.screener.compute")
        self.data_loader = data_loader
        self.last_filter_breakdown: List[Dict[str, Any]] = []
        self.last_debug_stats: Dict[str, Any] = {}

    def get_last_filter_breakdown(self) -> List[Dict[str, Any]]:
        """Return the most recent filter breakdown generated by compute."""
        return [dict(step) for step in self.last_filter_breakdown]

    def get_last_debug_stats(self) -> Dict[str, Any]:
        """Return the most recent debug stats for the screener computation."""
        return dict(self.last_debug_stats)
    
    async def compute(
        self,
        snaps: List[Any],
        min_price: Optional[float] = None,
        max_price: Optional[float] = None,
        min_volume: Optional[float] = None,
        min_change_percent: Optional[float] = None,
        max_change_percent: Optional[float] = None,
        min_relative_volume: Optional[float] = None,
        order_by: str = "rv14",
        limit: int = 200,
        technical_filters: Optional[Dict[str, Any]] = None,
        exclude_etfs: bool = True,
        asset_types: Optional[List[str]] = None,
        market_cap_min: Optional[int] = None,
        market_cap_max: Optional[int] = None,
        float_min: Optional[int] = None,
        float_max: Optional[int] = None,
    ) -> List[dict]:
        """Compute filtered and sorted screener results from market snapshots.

        Args:
            snaps: List of market snapshots
            min_price: Minimum price filter (for yesterday's close)
            max_price: Maximum price filter (for yesterday's close)
            min_volume: Minimum volume for liquidity
            min_change_percent: Minimum % change from yesterday's close
            max_change_percent: Maximum % change from yesterday's close
            min_relative_volume: Minimum relative volume (RV14) filter
            order_by: Field to sort by (rv14 or avg_volume)
            limit: Maximum number of results to return
            technical_filters: Optional dict of technical analysis filters
            exclude_etfs: Whether to exclude ETFs (default: True)
            asset_types: Optional list of asset types to include (e.g., ["CS", "ETF"])
            market_cap_min: Minimum market cap filter (in dollars)
            market_cap_max: Maximum market cap filter (in dollars)
            float_min: Minimum public float filter (in dollars)
            float_max: Maximum public float filter (in dollars)

        Returns:
            List of screener result dictionaries
        """
        total_snapshots = len(snaps)
        filter_breakdown: List[Dict[str, Any]] = []
        debug_counts: Dict[str, Any] = {
            "total_snapshots": total_snapshots,
        }
        previous_count: Optional[int] = None

        def add_step(label: str, count: int) -> None:
            nonlocal previous_count
            count = max(int(count or 0), 0)
            removed = None
            if previous_count is not None:
                removed = max(previous_count - count, 0)
            filter_breakdown.append(
                {
                    "label": label,
                    "count": count,
                    "removed": removed if removed is not None else 0,
                }
            )
            previous_count = count

        add_step("Total symbols fetched", total_snapshots)

        def _to_float(value: Any) -> Optional[float]:
            try:
                if value is None:
                    return None
                return float(value)
            except (TypeError, ValueError):
                return None

        # Debug: log structure of first snapshot
        if snaps and self.logger.isEnabledFor(logging.DEBUG):
            self.logger.debug(
                "First snapshot structure: %s", snaps[0] if len(snaps) > 0 else "empty"
            )

        # Phase 1: apply exchange eligibility and gather necessary fields
        filtered_by_exchange = 0
        exchange_eligible: List[Dict[str, Any]] = []
        for snapshot in snaps:
            data = extract_snapshot_data(snapshot)
            ticker = data["ticker"]
            exchange = data["exchange"]
            current_price = _to_float(data["price"])

            if not ticker or current_price is None:
                continue

            if not is_allowed_exchange(exchange):
                filtered_by_exchange += 1
                continue

            day_data = snapshot.get("day", {}) or {}
            exchange_eligible.append(
                {
                    "ticker": ticker,
                    "current_price": current_price,
                    "snapshot": snapshot,
                    "day": day_data,
                }
            )

        debug_counts["filtered_by_exchange"] = filtered_by_exchange
        add_step("After exchange eligibility", len(exchange_eligible))

        # Phase 2: enforce availability of prior-day OHLC data from market_data
        missing_prior_day = 0
        prior_day_ready: List[Dict[str, Any]] = []
        for entry in exchange_eligible:
            day = entry["day"]
            prior_open = _to_float(day.get("o"))
            prior_high = _to_float(day.get("h"))
            prior_low = _to_float(day.get("l"))
            prior_close = _to_float(day.get("c"))
            prior_volume = _to_float(day.get("v"))

            if (
                prior_open is None
                or prior_high is None
                or prior_low is None
                or prior_close is None
                or prior_volume is None
            ):
                missing_prior_day += 1
                continue

            entry.update(
                {
                    "prior_open": prior_open,
                    "prior_high": prior_high,
                    "prior_low": prior_low,
                    "prior_close": prior_close,
                    "prior_volume": prior_volume,
                }
            )
            prior_day_ready.append(entry)

        debug_counts["missing_prior_day"] = missing_prior_day
        add_step("After prior-day data", len(prior_day_ready))

        # Phase 3: apply database filter (market cap / float) only once
        rows: List[dict] = []
        processed_count = 0
        filtered_count = 0
        price_filtered_count = 0
        volume_filtered_count = 0
        rv_filtered_count = 0
        asset_type_filtered_count = 0
        change_min_filtered_count = 0
        change_max_filtered_count = 0

        # Apply database-level fundamentals filters
        if (
            market_cap_min is not None
            or market_cap_max is not None
            or float_min is not None
            or float_max is not None
        ):
            from app.services.screener.ticker_filter import (
                FilterCriteria,
                get_filtered_tickers,
            )

            self.logger.info(
                "Applying database filters: market_cap=(%s, %s), float=(%s, %s)",
                market_cap_min,
                market_cap_max,
                float_min,
                float_max,
            )

            criteria = FilterCriteria(
                asset_types=asset_types if asset_types else None,
                market_cap_min=market_cap_min,
                market_cap_max=market_cap_max,
                float_min=float_min,
                float_max=float_max,
            )

            allowed_tickers = await get_filtered_tickers(criteria)
            allowed_ticker_set = set(allowed_tickers)

            filtered_prior_day_ready = [
                entry
                for entry in prior_day_ready
                if entry["ticker"] in allowed_ticker_set
            ]

            debug_counts["database_filtered_removed"] = (
                len(prior_day_ready) - len(filtered_prior_day_ready)
            )
            prior_day_ready = filtered_prior_day_ready
        else:
            debug_counts["database_filtered_removed"] = 0

        add_step("After fundamentals (market cap / float)", len(prior_day_ready))

        working_entries = prior_day_ready

        # Price filters
        if min_price is not None or max_price is not None:
            filter_min = min_price if min_price is not None else 0.0
            filter_max = max_price if max_price is not None else float("inf")
            next_entries = []
            for entry in working_entries:
                current_price = entry["current_price"]
                prior_close = entry["prior_close"]
                if passes_price_filter(current_price, prior_close, filter_min, filter_max):
                    next_entries.append(entry)
                else:
                    price_filtered_count += 1
            working_entries = next_entries
        add_step("After price range filter", len(working_entries))

        # Volume filter
        if min_volume is not None:
            next_entries = []
            for entry in working_entries:
                prior_volume = entry["prior_volume"]
                if passes_volume_filter(prior_volume, min_volume):
                    next_entries.append(entry)
                else:
                    volume_filtered_count += 1
            working_entries = next_entries
        add_step("After volume filter", len(working_entries))

        # Relative volume filter
        if min_relative_volume is not None:
            next_entries = []
            for entry in working_entries:
                rv_value = _to_float(entry["snapshot"].get("rv14")) or 0.0
                if rv_value >= min_relative_volume:
                    next_entries.append(entry)
                else:
                    rv_filtered_count += 1
            working_entries = next_entries
        add_step("After relative volume filter", len(working_entries))

        # Asset type / ETF filtering
        next_entries = []
        for entry in working_entries:
            ticker = entry["ticker"]
            if asset_types and len(asset_types) > 0:
                ticker_type = "ETF" if is_likely_etf(ticker) else "CS"
                if ticker_type not in asset_types:
                    asset_type_filtered_count += 1
                    continue
            elif exclude_etfs and is_likely_etf(ticker):
                asset_type_filtered_count += 1
                continue
            next_entries.append(entry)
        working_entries = next_entries
        add_step("After asset type / ETF filter", len(working_entries))

        # Change percent filters
        if min_change_percent is not None or max_change_percent is not None:
            next_entries = []
            for entry in working_entries:
                current_price = entry["current_price"]
                prior_close = entry["prior_close"]
                change_close_pct = (
                    ((current_price - prior_close) / prior_close) * 100
                    if prior_close > 0
                    else 0.0
                )
                entry["change_close_pct"] = change_close_pct
                entry["change_close"] = change_close_pct

                if min_change_percent is not None and change_close_pct < min_change_percent:
                    change_min_filtered_count += 1
                    continue
                if max_change_percent is not None and change_close_pct > max_change_percent:
                    change_max_filtered_count += 1
                    continue
                next_entries.append(entry)
            working_entries = next_entries
        else:
            for entry in working_entries:
                current_price = entry["current_price"]
                prior_close = entry["prior_close"]
                entry["change_close_pct"] = (
                    ((current_price - prior_close) / prior_close) * 100
                    if prior_close > 0
                    else 0.0
                )
                entry["change_close"] = entry["change_close_pct"]
        add_step("After change% filters", len(working_entries))

        rows = []
        for entry in working_entries:
            ticker = entry["ticker"]
            current_price = entry["current_price"]
            prior_open = entry["prior_open"]
            prior_high = entry["prior_high"]
            prior_low = entry["prior_low"]
            prior_close = entry["prior_close"]
            prior_volume = entry["prior_volume"]
            snapshot = entry["snapshot"]

            rows.append(
                {
                    "ticker": ticker,
                    "price": current_price,
                    "last_trade_price": current_price,
                    "prev_open": prior_open,
                    "prev_high": prior_high,
                    "prev_low": prior_low,
                    "prev_close": prior_close,
                    "prev_volume": prior_volume,
                    "today_vol": _to_float(snapshot.get("today_vol")) or 0.0,
                    "rv14": _to_float(snapshot.get("rv14")) or 0.0,
                    "rv_lw": _to_float(snapshot.get("rv_lw")) or 0.0,
                    "change_close": entry["change_close"],
                    "change_close_pct": entry["change_close_pct"],
                    "type": snapshot.get("type"),
                    "primary_exchange": snapshot.get("primary_exchange") or entry["snapshot"].get("exchange"),
                    "sic_description": snapshot.get("sic_description"),
                    "market_cap": snapshot.get("market_cap"),
                    "public_float": snapshot.get("public_float"),
                }
            )
            processed_count += 1

        filtered_count = (
            price_filtered_count
            + volume_filtered_count
            + rv_filtered_count
            + asset_type_filtered_count
            + change_min_filtered_count
            + change_max_filtered_count
        )
        
        # Sort results
        sort_key = {
            "rv14": lambda x: x.get("rv14") or 0.0,
            "rv_lw": lambda x: x.get("rv_lw") or 0.0,
            "today_vol": lambda x: x.get("today_vol") or 0.0,
            "avg_volume": lambda x: x.get("prev_volume") or 0.0,
            "change_close": lambda x: x.get("change_close", 0.0),
        }.get(order_by, lambda x: x.get("rv14") or 0.0)
        rows.sort(key=sort_key, reverse=True)

        debug_counts.update(
            {
                "processed_count": processed_count,
                "price_filtered": price_filtered_count,
                "volume_filtered": volume_filtered_count,
                "rv_filtered": rv_filtered_count,
                "asset_type_filtered": asset_type_filtered_count,
                "change_min_filtered": change_min_filtered_count,
                "change_max_filtered": change_max_filtered_count,
            }
        )

        rows_before_technical = len(rows)
        if technical_filters:
            rows = await self._apply_technical_filters(rows, technical_filters, is_historical=False)
            technical_filtered_count = max(rows_before_technical - len(rows), 0)
        else:
            technical_filtered_count = 0

        filtered_count += technical_filtered_count
        debug_counts["technical_filtered"] = technical_filtered_count

        add_step("After technical filters", len(rows))

        if limit is not None:
            limited_rows = rows[:limit]
        else:
            limited_rows = rows

        limit_removed = max(len(rows) - len(limited_rows), 0)
        debug_counts["limit_removed"] = limit_removed
        add_step("Final results (limit applied)", len(limited_rows))

        # Log filtering statistics
        self.logger.info(
            "Screener: %s processed → %s results (filtered: %s, limit_removed: %s)",
            processed_count,
            len(limited_rows),
            filtered_count,
            limit_removed,
        )

        self.last_filter_breakdown = filter_breakdown
        self.last_debug_stats = {
            **debug_counts,
            "filter_breakdown": filter_breakdown,
        }

        return limited_rows
    
    async def _apply_technical_filters(
        self,
        rows: List[dict],
        technical_filters: Dict[str, Any],
        is_historical: bool = False
    ) -> List[dict]:
        """Apply technical analysis filters to screener results.
        
        Args:
            rows: List of screener result dicts
            technical_filters: Dict of technical filter criteria
            is_historical: Whether we're in historical mode (affects bar retrieval)
            
        Returns:
            Filtered list of rows
        """
        from app.lib.technical_analysis import (
            find_swing_points,
            find_equal_levels,
            find_support_resistance,
            is_price_near_level,
        )
        
        filtered_rows = []
        
        for row in rows:
            symbol = row["ticker"]
            current_price = row["price"]
            
            # Get bars for technical analysis
            if is_historical:
                bars = row.get("_historical_bars", [])
            else:
                # For live mode, would need to track recent bars
                # For now, skip technical filters in live mode
                bars = []
            
            passed = True
            
            # Near resistance filter
            if technical_filters.get("near_resistance") and bars:
                swing_points = find_swing_points(bars)
                resistance_levels = find_support_resistance(swing_points, is_support=False)
                if not any(is_price_near_level(current_price, level, tolerance_pct=2.0) 
                          for level in resistance_levels):
                    passed = False
            
            # Near support filter
            if technical_filters.get("near_support") and bars:
                swing_points = find_swing_points(bars)
                support_levels = find_support_resistance(swing_points, is_support=True)
                if not any(is_price_near_level(current_price, level, tolerance_pct=2.0) 
                          for level in support_levels):
                    passed = False
            
            # Equal highs filter
            if technical_filters.get("has_equal_highs") and bars:
                swing_points = find_swing_points(bars)
                equal_levels = find_equal_levels(swing_points, is_support=False, tolerance_pct=1.0)
                if not equal_levels:
                    passed = False
            
            # Equal lows filter
            if technical_filters.get("has_equal_lows") and bars:
                swing_points = find_swing_points(bars)
                equal_levels = find_equal_levels(swing_points, is_support=True, tolerance_pct=1.0)
                if not equal_levels:
                    passed = False
            
            # Above 90-day high filter
            if technical_filters.get("above_90day_high"):
                if row.get("ninety_day_high") and current_price <= row["ninety_day_high"]:
                    passed = False
            
            # Below 90-day low filter
            if technical_filters.get("below_90day_low"):
                if row.get("ninety_day_low") and current_price >= row["ninety_day_low"]:
                    passed = False
            
            # Relative volume filter
            if technical_filters.get("relative_volume_min"):
                min_rv = technical_filters["relative_volume_min"]
                if row.get("rv14", 0) < min_rv:
                    passed = False
            
            if passed:
                filtered_rows.append(row)
        
        return filtered_rows

